allowBuilds:
  unrs-resolver: false
minimumReleaseAgeExclude:
  - '@es-joy/jsdoccomment@0.95.0'
  - '@typescript-eslint/types@8.67.0'
  - eslint-config-ash-nazg@42.3.1
  - eslint-plugin-jsdoc@64.1.0
  - jsdoc-type-pratt-parser@9.1.1
  - '@passport-next/http-types@0.1.0 || 0.2.0'
  - '@passport-next/passport-types@0.2.0 || 0.3.0 || 0.3.1'
